#!/usr/bin/env node
// Writes the double-byte characters of Windows code page 932 (Shift_JIS as Windows has
// it, which the desktop tracker writes on Japanese Windows) as a C++ table:
//
//   node tools/gen_cp932.mjs > src/cp932_table.inc
//
// The characters come from the Shift_JIS decoder of the Encoding Standard, which reads
// code page 932: node's TextDecoder (with its full ICU, as node ships) and browsers give
// the same table. User-defined characters (lead bytes 0xF0-0xF9, private use code points)
// are left out: they mean nothing without the fonts made for them.

const range = (first, last) => Array.from({ length: last - first + 1 }, (_, i) => first + i);
const LEADS = [...range(0x81, 0x9F), ...range(0xE0, 0xFC)];
const TRAILS = [...range(0x40, 0x7E), ...range(0x80, 0xFC)];
const hex = (value, digits) => '0x' + value.toString(16).toUpperCase().padStart(digits, '0');

const decoder = new TextDecoder('shift_jis', { fatal: true });
const character = (lead, trail) => {
  try {
    const chars = [...decoder.decode(Uint8Array.of(lead, trail))];
    const code = chars.length === 1 ? chars[0].codePointAt(0) : 0;
    return code >= 0xE000 && code <= 0xF8FF ? 0 : code;
  } catch {
    return 0;
  }
};

// a check that this is code page 932 and not another Shift_JIS
if (character(0x81, 0x60) !== 0xFF5E || character(0x87, 0x40) !== 0x2460 || character(0xFA, 0x40) !== 0x2170)
  throw new Error('this TextDecoder does not read Shift_JIS as code page 932');

const lines = [
  '// Windows code page 932: the character of each double-byte code, by lead byte',
  '// (0x81-0x9F, then 0xE0-0xFC) and trail byte (0x40-0x7E, then 0x80-0xFC), 0 where there is',
  '// none. User-defined characters are left out. Generated by tools/gen_cp932.mjs: do not',
  '// edit.',
  `static const uint16_t CP932_DOUBLE[${LEADS.length}][${TRAILS.length}] = {`,
];
let count = 0;
for (const lead of LEADS) {
  const codes = TRAILS.map(trail => character(lead, trail));
  count += codes.filter(Boolean).length;
  lines.push(`\t{ // ${hex(lead, 2)}`);
  for (let i = 0; i < codes.length; i += 12)
    lines.push('\t\t' + codes.slice(i, i + 12).map(code => hex(code, 4)).join(', ') + ',');
  lines.push('\t},');
}
lines.push('};', `// ${count} characters`, '');
process.stdout.write(lines.join('\n'));
