// Generate decoder profiles from the same assembled drivers the exporter uses.
// Code bytes and relocations are checked in full; only exporter-patched tables
// are excluded. Regenerate at build time, so source changes cannot silently keep
// accepting an obsolete driver layout.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [directory, output] = process.argv.slice(2);
if (!directory || !output) throw new Error('usage: nsf_driver_profiles.mjs <headers> <output>');
const chips = ['2A03', 'VRC6', 'VRC7', 'FDS', 'MMC5', 'N163', 'S5B', 'ALL'];
const profiles = chips.map(chip => {
  const source = readFileSync(join(directory, `drv_${chip.toLowerCase()}.h`), 'utf8');
  const array = name => {
    const value = source.match(new RegExp(`\\b${name}\\[\\]\\s*=\\s*\\{([\\s\\S]*?)\\}`))?.[1];
    if (value === undefined) throw new Error(`missing ${name}`);
    return [...value.matchAll(/0x([0-9a-f]+)/gi)].map(m => parseInt(m[1], 16));
  };
  const constant = name => {
    const value = source.match(new RegExp(`\\b${name}\\s*=\\s*0x([0-9a-f]+)`, 'i'));
    return value ? parseInt(value[1], 16) : null;
  };
  const tables = [...source.match(new RegExp(`DRIVER_FREQ_TABLE_${chip}\\[\\]\\s*=\\s*\\{([\\s\\S]*?)\\}`))[1]
    .matchAll(/0x([0-9a-f]+),\s*CDetuneTable::DETUNE_(\w+)/gi)]
    .map(m => ({ at: parseInt(m[1], 16), type: m[2] }));
  const bytes = array(`DRIVER_${chip}`);
  const identity = array(`NSFDRV_${chip}`);
  if (String.fromCharCode(...identity.slice(0, 6)) !== 'Dn-FT ' || identity[6] !== 2 || identity[7] !== 16)
    throw new Error('Update the decoder and its tests before accepting a new driver version');
  return { chip, identity, code: bytes.map(b => b.toString(16).padStart(2, '0')).join(''),
    words: array(`DRIVER_RELOC_WORD_${chip}`), addresses: array(`DRIVER_RELOC_ADR_${chip}`), tables,
    vibrato: constant(`VIBRATO_TABLE_LOCATION_${chip}`),
    channelType: chip === 'N163' ? constant('FT_CH_TYPE_ADR') : null,
    update: chip === 'ALL' ? constant('FT_UPDATE_EXT_ADR') : null,
    enable: chip === 'ALL' ? constant('FT_CH_ENABLE_ADR') : null };
});
writeFileSync(output, '// Generated by tools/nsf_driver_profiles.mjs; do not edit.\nexport default ' + JSON.stringify(profiles) + ';\n');
